language: go

go:
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip

before_script:
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
  - go get -v -t ./...
  - make test
